name: CI

on:
  push:
  pull_request:
  pull_request_target:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:   # add this line

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Success
        run: echo "It is successful. 1234"
