name: Lint

# on:
#   push:
#     branches: ["**"]
#   workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Configure tool cache path
        run: echo "RUNNER_TOOL_CACHE=$HOME/hostedtoolcache" >> "$GITHUB_ENV"

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run lint
        run: node -e "console.log('lint complete')"
